[build]
  base = "u08-frontend"
  command = "npm run build"
  publish = "dist/u08-frontend/browser"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
